---
- name: Install required packages and Python modules
  hosts: all
  become: yes

  tasks:
    - name: Install apt packages
      apt:
        name:
          - vim
          - git
          - python3-pip
          - gawk
          - texinfo
          - libgmp-dev
          - libmpfr-dev
          - libmpc-dev
          - autoconf
          - automake
          - autotools-dev
          - curl
          - python3
          - build-essential
          - bison
          - flex
          - gperf
          - libtool
          - patchutils
          - bc
          - zlib1g-dev
          - libexpat-dev
          - swig3.0
          - libjpeg-dev
          - lsb-core
          - doxygen
          - python-sphinx
          - sox
          - graphicsmagick-libmagick-dev-compat
          - libsdl2-dev
          - libswitch-perl
          - libftdi1-dev
          - cmake
          - scons
          - libsndfile1-dev
          - python-pip
        state: present
        update_cache: yes

    - name: Install Python 3 pip packages
      pip:
        name:
          - pyelftools
          - twisted
          - prettytable
          - openpyxl
          - xlsxwriter
          - pyyaml
          - numpy
          - configparser
          - pyvcd
        executable: pip3

    - name: Install Python 2 pip packages
      pip:
        name: configparser
        executable: pip2
