---
- name: Install required packages and Python dependencies
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install packages using apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git
        - python3-pip
        - gawk
        - texinfo
        - libgmp-dev
        - libmpfr-dev
        - libmpc-dev
        - autoconf
        - automake
        - autotools-dev
        - curl
        - python3
        - libmpc-dev
        - libmpfr-dev
        - libgmp-dev
        - gawk
        - build-essential
        - bison
        - flex
        - zlib1g-dev
        - libexpat-dev
        - swig3.0
        - libjpeg-dev
        - lsb-core
        - doxygen
        - python-sphinx
        - sox
        - graphicsmagick-libmagick-dev-compat
        - libsdl2-dev
        - libswitch-perl
        - libftdi1-dev
        - cmake
        - scons
        - libsndfile1-dev

    - name: Install pyelftools using pip3
      pip:
        name: pyelftools
        executable: pip3

    - name: Install Python dependencies using pip3
      pip:
        name: "{{ item }}"
        executable: pip3
      loop:
        - twisted
        - prettytable
        - pyelftools
        - openpyxl
        - xlsxwriter
        - pyyaml
        - numpy
        - configparser
        - pyvcd

    - name: Install python-pip
      apt:
        name: python-pip
        state: present

    - name: Install configparser using pip2
      pip:
        name: configparser
        executable: pip2

